import { Router } from 'express';
import * as ai from '../services/openai.js';
import * as dfs from '../services/dataforseo.js';
import { log } from '../services/logger.js';

const router = Router();

const OUR_DOMAINS = ['schreinerhelden.de', 'ihr-moebel-schreiner.de'];

router.post('/content', async (req, res) => {
  try {
    const { keyword, context, template = 'article' } = req.body;
    if (!keyword) return res.status(400).json({ error: 'Keyword required' });
    const content = await ai.generateContentDraft(keyword, context || '', '', '');
    res.json({ content, keyword, template });
  } catch (error) {
    log.error('AI content error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// ── HTML Landing Page Generator ──
router.post('/landing-page', async (req, res) => {
  try {
    const { keyword, region, service, domain = 'sh' } = req.body;
    if (!keyword) return res.status(400).json({ error: 'Keyword required' });

    log.info(`Generating HTML LP: "${keyword}" ${region}`);

    // Step 1: Get SERP data
    let serpSummary = '';
    try {
      const searchKey = region ? `${keyword} ${region}` : keyword;
      const serpData = await dfs.serpOrganic(searchKey);
      const items = serpData.tasks?.[0]?.result?.[0]?.items || [];
      serpSummary = items
        .filter(i => i.type === 'organic').slice(0, 10)
        .map((r, i) => `${i + 1}. ${r.title} (${r.domain}) — ${(r.description || '').slice(0, 120)}`)
        .join('\n');
    } catch (e) { log.warn('SERP fetch for LP failed:', e.message); }

    // Step 2: Get longtails
    let longtailSummary = '';
    try {
      const lt = await ai.generateLongtails(keyword, domain);
      longtailSummary = (lt.keywords || []).map(k => k.keyword).join(', ');
    } catch (e) { log.warn('Longtails for LP failed:', e.message); }

    // Step 3: Generate HTML
    let html = await ai.generateHtmlLandingPage(keyword, region || '', service || keyword, serpSummary, longtailSummary);

    // Step 4: Generate Schema.org JSON-LD and inject into HTML
    try {
      const schemaRoute = await import('./schema.js');
      // Build schemas directly (reuse logic from schema route)
      const schemas = [];

      // LocalBusiness
      const bizUrl = domain === 'ims' ? 'https://ihr-moebel-schreiner.de' : 'https://schreinerhelden.de';
      const bizName = domain === 'ims' ? 'Ihr Möbel-Schreiner Murrhardt' : 'Schreinerhelden GmbH & Co. KG';

      schemas.push({
        '@context': 'https://schema.org',
        '@type': ['LocalBusiness', 'HomeAndConstructionBusiness'],
        '@id': `${bizUrl}/#organization`,
        name: bizName,
        url: bizUrl,
        telephone: '+4971929789012',
        email: 'info@schreinerhelden.de',
        address: {
          '@type': 'PostalAddress',
          streetAddress: 'Lindenstraße 9-15',
          addressLocality: 'Murrhardt',
          addressRegion: 'Baden-Württemberg',
          postalCode: '71540',
          addressCountry: 'DE',
        },
        geo: { '@type': 'GeoCoordinates', latitude: 48.9803, longitude: 9.5789 },
        priceRange: '€€€',
        areaServed: { '@type': 'City', name: region || 'Stuttgart' },
      });

      // Service
      schemas.push({
        '@context': 'https://schema.org',
        '@type': 'Service',
        name: service || keyword,
        description: `${service || keyword} von ${bizName} in ${region || 'Stuttgart'}. Individuelle Maßfertigung aus der eigenen Werkstatt in Murrhardt.`,
        provider: { '@type': 'LocalBusiness', '@id': `${bizUrl}/#organization`, name: bizName },
        areaServed: { '@type': 'City', name: region || 'Stuttgart' },
        serviceType: keyword,
      });

      // BreadcrumbList
      const slug = keyword.toLowerCase()
        .replace(/ä/g, 'ae').replace(/ö/g, 'oe').replace(/ü/g, 'ue').replace(/ß/g, 'ss')
        .replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      schemas.push({
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Start', item: bizUrl },
          { '@type': 'ListItem', position: 2, name: keyword, item: `${bizUrl}/${slug}/` },
        ],
      });

      // Build JSON-LD block
      const schemaHtml = schemas.map(s =>
        `<script type="application/ld+json">\n${JSON.stringify(s, null, 2)}\n</script>`
      ).join('\n');

      // Remove any GPT-generated JSON-LD (often broken) and inject our clean version
      html = html.replace(/<script\s+type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/gi, '');

      // Inject at top of HTML (after first tag or at beginning)
      const schemaComment = `\n<!-- Schema.org JSON-LD (auto-generated by MEOS:SEO) -->\n${schemaHtml}\n`;
      if (html.includes('<!--')) {
        // Insert after the comment block at the top
        html = html.replace(/(<!--[\s\S]*?-->\s*)/, `$1${schemaComment}`);
      } else {
        html = schemaComment + html;
      }

      log.info(`Schema.org injected: ${schemas.length} schemas for "${keyword}"`);
    } catch (e) {
      log.warn('Schema injection failed (non-critical):', e.message);
    }

    // Count words (strip HTML tags + JSON-LD)
    const textOnly = html
      .replace(/<script[^>]*>[\s\S]*?<\/script>/gi, '')
      .replace(/<[^>]*>/g, ' ')
      .replace(/\s+/g, ' ').trim();
    const wordCount = textOnly.split(' ').filter(w => w.length > 0).length;

    res.json({ html, keyword, region, wordCount });
  } catch (error) {
    log.error('AI landing page error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// ── Wettbewerber-Diagnose ──
router.post('/competitor-diagnosis', async (req, res) => {
  try {
    const { keyword, region } = req.body;
    if (!keyword) return res.status(400).json({ error: 'Keyword required' });

    log.info(`Competitor diagnosis: "${keyword}" ${region}`);

    const searchKey = region ? `${keyword} ${region}` : keyword;

    // Step 1: SERP analysis
    const serpData = await dfs.serpOrganic(searchKey);
    const items = serpData.tasks?.[0]?.result?.[0]?.items || [];
    const organic = items.filter(i => i.type === 'organic').slice(0, 10);

    // Find our position
    const ours = organic.find(r => OUR_DOMAINS.some(d => (r.domain || '').includes(d)));
    const ourData = ours
      ? `Position ${ours.rank_group}: ${ours.title} (${ours.domain}) — ${ours.url}`
      : 'Nicht in TOP 10 gefunden';

    const serpSummary = organic.map((r, i) =>
      `Pos ${r.rank_group || i + 1}: ${r.title} (${r.domain}) — ${(r.description || '').slice(0, 150)}`
    ).join('\n');

    // Step 2: Backlink data for top 5 competitors
    let competitorDetails = '';
    const topDomains = organic.slice(0, 5).map(r => r.domain).filter(Boolean);
    for (const dom of topDomains) {
      try {
        const bl = await dfs.backlinksSummary(dom);
        const summary = bl.tasks?.[0]?.result?.[0];
        if (summary) {
          competitorDetails += `${dom}: Backlinks=${summary.backlinks || 0}, Ref.Domains=${summary.referring_domains || 0}, DA=${summary.rank || 0}\n`;
        }
        await new Promise(r => setTimeout(r, 500)); // Rate limit
      } catch (e) {
        competitorDetails += `${dom}: Daten nicht verfügbar\n`;
      }
    }

    // Also get our backlinks
    let ourBacklinks = '';
    try {
      const ourBl = await dfs.backlinksSummary('schreinerhelden.de');
      const ourSummary = ourBl.tasks?.[0]?.result?.[0];
      if (ourSummary) {
        ourBacklinks = `schreinerhelden.de: Backlinks=${ourSummary.backlinks || 0}, Ref.Domains=${ourSummary.referring_domains || 0}, DA=${ourSummary.rank || 0}`;
      }
    } catch {}

    // Step 3: GPT-4o Diagnosis
    const diagnosis = await ai.generateCompetitorDiagnosis(
      keyword, region || 'Stuttgart',
      serpSummary,
      `${ourData}\n${ourBacklinks}`,
      competitorDetails
    );

    // Add raw data
    diagnosis.rawSerp = organic.map(r => ({
      position: r.rank_group,
      domain: r.domain,
      title: r.title,
      url: r.url,
      isOurs: OUR_DOMAINS.some(d => (r.domain || '').includes(d)),
    }));

    res.json(diagnosis);
  } catch (error) {
    log.error('Competitor diagnosis error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

router.post('/longtails', async (req, res) => {
  try {
    const { seedKeyword, domain = 'sh' } = req.body;
    if (!seedKeyword) return res.status(400).json({ error: 'Seed keyword required' });
    const result = await ai.generateLongtails(seedKeyword, domain);
    res.json(result);
  } catch (error) {
    log.error('AI longtails error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

router.post('/aeo-questions', async (req, res) => {
  try {
    const { keyword } = req.body;
    if (!keyword) return res.status(400).json({ error: 'Keyword required' });
    const result = await ai.generateAeoQuestions(keyword);
    res.json(result);
  } catch (error) {
    log.error('AI AEO error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// ── Social Content Multiplier ──
router.post('/social', async (req, res) => {
  try {
    const { channel, keyword, region, lpSummary } = req.body;
    if (!channel || !keyword) return res.status(400).json({ error: 'Channel and keyword required' });

    log.info(`Social content: ${channel} for "${keyword}"`);
    const result = await ai.generateSocialContent(channel, keyword, region || '', lpSummary || '');
    res.json({ channel, keyword, region, content: result });
  } catch (error) {
    log.error('Social content error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

// ── Bulk Social: All channels at once ──
router.post('/social/bulk', async (req, res) => {
  try {
    const { keyword, region, lpSummary, channels = ['gbp', 'instagram', 'pinterest', 'blog'] } = req.body;
    if (!keyword) return res.status(400).json({ error: 'Keyword required' });

    log.info(`Bulk social: ${channels.join(', ')} for "${keyword}"`);
    const results = {};
    for (const ch of channels) {
      try {
        results[ch] = await ai.generateSocialContent(ch, keyword, region || '', lpSummary || '');
      } catch (e) {
        results[ch] = { error: e.message };
        log.warn(`Social ${ch} failed:`, e.message);
      }
    }

    res.json({ keyword, region, channels: results });
  } catch (error) {
    log.error('Bulk social error:', error.message);
    res.status(500).json({ error: error.message });
  }
});

export default router;
